{"variants":[{"paths":["\/documentation\/soulvercore\/evaluationresult\/error(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"seeAlsoSections":[{"generated":true,"title":"Nil answer cases","identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/none","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/pending","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/failed"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/app.soulver.core\/documentation\/SoulverCore","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"kind":"text","text":"("},{"text":"EvaluationError","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationError","kind":"typeIdentifier","preciseIdentifier":"s:11SoulverCore15EvaluationErrorO"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["macOS"]}]}],"identifier":{"url":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/error(_:)","interfaceLanguage":"swift"},"metadata":{"title":"EvaluationResult.error(_:)","symbolKind":"case","externalID":"s:11SoulverCore16EvaluationResultO5erroryAcA0C5ErrorOcACmF","modules":[{"name":"SoulverCore"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:11SoulverCore15EvaluationErrorO","text":"EvaluationError"},{"text":")","kind":"text"}],"role":"symbol"},"references":{"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/failed":{"kind":"symbol","type":"topic","url":"\/documentation\/soulvercore\/evaluationresult\/failed","abstract":[{"text":"The network could not deliver a result (perhaps due to connectivity problems or a service outage)","type":"text"}],"role":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/failed","title":"EvaluationResult.failed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}]},"doc://app.soulver.core/documentation/SoulverCore/EvaluationError":{"url":"\/documentation\/soulvercore\/evaluationerror","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"EvaluationError"}],"kind":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationError","abstract":[{"text":"All errors that SoulverCore can produce as a result of a calculation","type":"text"}],"type":"topic","title":"EvaluationError","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EvaluationError"}]},"doc://app.soulver.core/documentation/SoulverCore":{"kind":"symbol","role":"collection","url":"\/documentation\/soulvercore","abstract":[{"text":"A powerful natural language calculation engine","type":"text"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore","type":"topic","title":"SoulverCore"},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult":{"type":"topic","title":"EvaluationResult","url":"\/documentation\/soulvercore\/evaluationresult","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EvaluationResult","kind":"identifier"}],"abstract":[{"text":"Represents the underlying data of a result of a SoulverCore calculation","type":"text"}],"navigatorTitle":[{"text":"EvaluationResult","kind":"identifier"}]},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/error(_:)":{"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/soulvercore\/evaluationresult\/error(_:)","role":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/error(_:)","title":"EvaluationResult.error(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":"("},{"text":"EvaluationError","kind":"typeIdentifier","preciseIdentifier":"s:11SoulverCore15EvaluationErrorO"},{"text":")","kind":"text"}]},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/none":{"kind":"symbol","type":"topic","url":"\/documentation\/soulvercore\/evaluationresult\/none","abstract":[{"text":"A null result","type":"text"}],"role":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/none","title":"EvaluationResult.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}]},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/pending":{"kind":"symbol","type":"topic","abstract":[{"text":"A result that must be fetched asyncronously (probably over a network)","type":"text"}],"url":"\/documentation\/soulvercore\/evaluationresult\/pending","role":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/pending","title":"EvaluationResult.pending","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pending"}]}}}